/**
 * EQUITY / INSIGHT — 2026-08-21 Market Ledger.
 * Style contract: ink-green research spine, warm-paper ledger, rare brass evidence rules.
 * Values, timestamps, tickers and citations use the analytical mono layer; serif is reserved for thesis and narrative.
 */
import { useEffect, useState } from "react";
import { ArrowRight, ArrowUpRight, CalendarDays, ChevronRight, CircleAlert, FileArchive, Landmark, Layers3, ShieldCheck, TrendingDown, TrendingUp } from "lucide-react";

export type ReportLanguage = "CN" | "TW" | "EN";
type Mode = "education" | "analysis";

const heroImage = `${import.meta.env.BASE_URL}equity-insight-hero_91085892.jpg`;

type Card = { tab: string; title: string; metric: string; fact: string; education: string; analysis: string; next: string; source: string };
type Watch = { event: string; time: string; exposure: string; learn: string; shortcut: string; positive: string; negative: string };

const copy: Record<ReportLanguage, any> = {
  CN: {
    locale: "简体中文主报告", switches: ["繁中", "简中", "EN"], edition: "BIT DAILY / 2026.08.21", nav: ["市场主线", "证据条目", "今日验证", "来源审计"], sourceNote: "完成收市、延迟盘中报价和观点分层呈现。", side: "利率减压失败，\n消费重新被测试。",
    ledger: "THE MARKET LEDGER / 21 AUG 2026", cut: "数据截点 · 11:11 HKT", strap: "美股 08.20 收盘 · 港股 08.20 收盘 + 08.21 盘中 · 下一美股交易日",
    titleA: "利率反弹与", titleB: "消费忧虑", titleC: "重回定价中心。", hero: "财政部买回带来的长端利率减压只维持一天。收益率、油价与Walmart的销售放缓共同打断反弹，市场重新交易通胀、贴现率与消费者承受力。",
    thesisLabel: "一句话主线", thesis: "昨日的 rate-relief 被反向验证：长端收益率重升，Walmart没有确认消费韧性；在利率和油价降温前，反弹仍须被视为待验证而非既定趋势。", auditLabel: "Yesterday → Today", audit: "8月20日的两个关键验证项均出现反面结果：收益率未续降，Walmart的同店销售也低于预期。",
    snapshotKicker: "01 / 完成交易时段", snapshotTitle: "反弹被打断，\n但并非成交量恐慌。", snapshotBody: "前三项是8月20日已完成美股收市。恒指明确为8月21日10:56:52 HKT的延迟盘中快照；不可写作收市。", statNames: ["S&P 500", "NASDAQ", "DOW", "恒指 · 盘中"], statNotes: ["8月20日收盘", "8月20日收盘", "8月20日收盘", "10:56 HKT / 延迟报价"],
    macroKicker: "02 / 宏观传导", macroTitle: "同一条链，\n压估值也压消费。", macroBody: "10Y上行4bp至4.69%，30Y上行4bp至5.24%；WTI升破US$87。收益率提高贴现率，油价则同时抬高通胀和居民可支配支出压力。", macroLabels: ["10Y yield", "30Y yield", "WTI crude"], macroValues: ["4.69%", "5.24%", "> US$87"], macroChanges: ["+4bp", "+4bp", "fifth day higher"],
    readingMode: "阅读模式", education: "投教阅读", analysis: "分析阅读", reading: "如何阅读", inference: "分析判断", fact: "事实", next: "下一步", sourceLabel: "来源", ledgerEntry: "研究条目", commonShortcut: "常见捷径", positive: "正面确认", negative: "负面确认", transmissionTitle: "市场传导", transmission: [["利率 → 估值", "前一日的长端减压在建立新定价机制前已经反转。"], ["油价 → 通胀／支出", "更高燃料成本同时体现在能源相对强势和更谨慎的消费读数。"], ["业绩 → 分化", "Deere与Moderna显示，公司级证据不应被压缩成指数叙事。"]], transmissionNote: "昨日的负面确认是一项风险条件，并不是对后续下跌的承诺。", signalsKicker: "03 / 事件到价格", signalsTitle: "不是所有下跌，\n都在说同一件事。", signalsBody: "每一条ledger entry都分开事实、价格反应、可推导范围和下一项验证；不要把单一公司反应外推成市场定论。",
    cards: [
      { tab: "MACRO / RATES", title: "买回操作未能持续压低长端", metric: "10Y 4.69% · 30Y 5.24%", fact: "财政部扩容买回后，美债长端收益率在次日均上行4bp；三大指数同步下跌。", education: "政策操作可短期改善流动性，却未必改变通胀、供给和风险溢价。先看收益率是否持续，再下估值结论。", analysis: "前日的 rate-relief 条件已失效；这是昨日价格行动最直接的宏观解释。", next: "若收益率回落且油价降温，才可重新讨论估值压力缓解。", source: "[1] Reuters · [3] Yahoo Finance" },
      { tab: "CONSUMER / EARNINGS", title: "Walmart把消费者担忧变成价格", metric: "WMT -9.2% · comps +2.6%", fact: "可比销售+2.6%，低于LSEG预期的+3.8%；客流+1.5%，同时公司上调全年销售增长指引至4–5%。", education: "读零售业绩要同时看客流、客单、促销、毛利和前瞻指引；上调全年销售不必然抵消短期需求减速。", analysis: "市场把高油价下的消费取舍和Q3 EPS压力放在更高权重，令这一业绩成为消费风险的负面确认。", next: "看同业能否稳定，以及降价能否保护销量／份额而不进一步压缩利润。", source: "[1] + [2] Reuters" },
      { tab: "DISPERSION / STOCKS", title: "事件股回吐，业绩上调仍被奖励", metric: "MRNA -23.5% · DE +6.9%", fact: "Moderna在前日临床数据大涨后回吐23.5%；Deere上调全年净利润预测后上涨6.9%。", education: "事件型跳升与持续盈利变化不是同一种信号；个股反应需回到催化剂的持续性。", analysis: "市场在宏观去风险中仍奖励可验证的公司级改善，因此不应把指数走弱直接写成全面基本面恶化。", next: "继续区分盈利／指引修正与短期主题、仓位或估值驱动的价格波动。", source: "[1] Reuters" },
      { tab: "SECTOR / OIL", title: "能源受益，消费与医疗同步承压", metric: "Energy +0.4% · Staples -1.93%", fact: "能源为主要上涨板块之一；必选消费、医疗和可选消费均为标普表现最弱组别。", education: "板块防御属性在油价冲击下会改变：能源受益于同一价格变量，消费却承担实际支出压力。", analysis: "这是油价从跨资产变量传导到行业相对收益的证据，而不是简单的“防御轮动”。", next: "观察油价是否止升，以及消费链弱势是否扩展至更多公司。", source: "[1] Reuters" },
    ] as Card[],
    watchKicker: "04 / 今天验证什么", watchTitle: "让利率、油价和同业，\n决定下一步叙事。", watchBody: "8月21日没有重大美国数据或大型业绩，因此盘前与开盘后更应关注旧主线是否继续扩散，而非寻找新的标题。",
    watches: [
      { event: "长端利率与油价", time: "整个下一美股交易日", exposure: "估值 + 通胀 + 消费的共同开关", learn: "把收益率、油价和成长／消费的相对表现放在同一条链里阅读。", shortcut: "不要将一段期货反弹等同于宏观压力解除。", positive: "10Y／30Y和油价同步回落，科技与消费停止扩大落后。", negative: "收益率、油价再上行，且成长／消费继续承压。" },
      { event: "Walmart同业 read-through", time: "美股盘前与开盘后", exposure: "COST、DLTR、ACI及可选消费", learn: "单一龙头业绩后，要检查同业表现才知道冲击是个股还是行业。", shortcut: "不要用单一EPS或单一日价格替代消费者整体结论。", positive: "同业稳定，销量和促销成效获重新定价。", negative: "同业继续走弱，说明消费者压力由Walmart扩散。" },
      { event: "香港中期业绩", time: "8月21日 · HKEX日程", exposure: "中国宏桥、中海油、紫金、中兴、贝壳、东方甄选等", learn: "先看完成公告中的盈利、现金流和指引，再把结果与指数方向关联。", shortcut: "不要把恒指早盘上涨当成任何一家公司业绩已被确认。", positive: "已披露业绩改善，提供宏观之外的基本面承接。", negative: "业绩分化或指引转弱，港股早盘强势不能延续。" },
    ] as Watch[],
    sourceKicker: "05 / 证据、时间戳与限制", sourceTitle: "事实先于叙事。", sourceBody: "美股收市和公司事实主要由Reuters核实；港股早盘来自带时间戳的延迟Yahoo报价，业绩日程来自HKEX。William本次上传的文件是流程规范，不含今日行情事实。", sourceCut: "资料截点：2026年8月21日 11:11 HKT · 盘中数据独立标注", archive: "历史归档", archives: ["阅读 2026.08.20", "阅读 2026.08.19", "阅读 2026.08.18"], footer: "内容由人工智能辅助整理，仅供市场信息、研究及投资者教育用途；不构成个性化投资建议、证券推荐、买卖或沽空指令，也不保证任何投资回报。",
  },
  TW: {
    locale: "繁體中文主報告", switches: ["繁中", "簡中", "EN"], edition: "BIT DAILY / 2026.08.21", nav: ["市場主線", "證據條目", "今日驗證", "來源稽核"], sourceNote: "完成收市、延遲盤中報價與觀點分層呈現。", side: "利率減壓失效，\n消費重新被測試。",
    ledger: "THE MARKET LEDGER / 21 AUG 2026", cut: "資料截點 · 11:11 HKT", strap: "美股 08.20 收市 · 港股 08.20 收市 + 08.21 盤中 · 下一美股交易日",
    titleA: "利率反彈與", titleB: "消費憂慮", titleC: "重回定價中心。", hero: "財政部買回帶來的長端利率減壓只維持一天。收益率、油價與Walmart的銷售放緩共同打斷反彈，市場重新交易通脹、貼現率與消費者承受力。",
    thesisLabel: "一句話主線", thesis: "昨日的 rate-relief 被反向驗證：長端收益率重升，Walmart沒有確認消費韌性；在利率和油價降溫前，反彈仍須被視為待驗證而非既定趨勢。", auditLabel: "Yesterday → Today", audit: "8月20日的兩個關鍵驗證項均出現反面結果：收益率未續降，Walmart的同店銷售也低於預期。",
    snapshotKicker: "01 / 完成交易時段", snapshotTitle: "反彈被打斷，\n但並非成交量恐慌。", snapshotBody: "前三項是8月20日已完成美股收市。恆指明確為8月21日10:56:52 HKT的延遲盤中快照；不可寫作收市。", statNames: ["S&P 500", "NASDAQ", "DOW", "恆指 · 盤中"], statNotes: ["8月20日收市", "8月20日收市", "8月20日收市", "10:56 HKT / 延遲報價"],
    macroKicker: "02 / 宏觀傳導", macroTitle: "同一條鏈，\n壓估值也壓消費。", macroBody: "10Y上行4bp至4.69%，30Y上行4bp至5.24%；WTI升破US$87。收益率提高貼現率，油價則同時抬高通脹和居民可支配支出壓力。", macroLabels: ["10Y yield", "30Y yield", "WTI crude"], macroValues: ["4.69%", "5.24%", "> US$87"], macroChanges: ["+4bp", "+4bp", "連升第五日"],
    readingMode: "閱讀模式", education: "投教閱讀", analysis: "分析閱讀", reading: "如何閱讀", inference: "分析判斷", fact: "事實", next: "下一步", sourceLabel: "來源", ledgerEntry: "研究條目", commonShortcut: "常見捷徑", positive: "正面確認", negative: "負面確認", transmissionTitle: "市場傳導", transmission: [["利率 → 估值", "前一日的長端減壓在建立新定價機制前已經反轉。"], ["油價 → 通脹／支出", "更高燃料成本同時體現在能源相對強勢和更謹慎的消費讀數。"], ["業績 → 分化", "Deere與Moderna顯示，公司級證據不應被壓縮成指數敘事。"]], transmissionNote: "昨日的負面確認是一項風險條件，並不是對後續下跌的承諾。", signalsKicker: "03 / 事件到價格", signalsTitle: "不是所有下跌，\n都在說同一件事。", signalsBody: "每一條ledger entry都分開事實、價格反應、可推導範圍和下一項驗證；不要把單一公司反應外推成市場定論。",
    cards: [
      { tab: "MACRO / RATES", title: "買回操作未能持續壓低長端", metric: "10Y 4.69% · 30Y 5.24%", fact: "財政部擴容買回後，美債長端收益率在次日均上行4bp；三大指數同步下跌。", education: "政策操作可短期改善流動性，卻未必改變通脹、供給和風險溢價。先看收益率是否持續，再下估值結論。", analysis: "前日的 rate-relief 條件已失效；這是昨日價格行動最直接的宏觀解釋。", next: "若收益率回落且油價降溫，才可重新討論估值壓力緩解。", source: "[1] Reuters · [3] Yahoo Finance" },
      { tab: "CONSUMER / EARNINGS", title: "Walmart把消費者憂慮變成價格", metric: "WMT -9.2% · comps +2.6%", fact: "可比銷售+2.6%，低於LSEG預期的+3.8%；客流+1.5%，同時公司上調全年銷售增長指引至4–5%。", education: "讀零售業績要同時看客流、客單、促銷、毛利和前瞻指引；上調全年銷售不必然抵消短期需求減速。", analysis: "市場把高油價下的消費取捨和Q3 EPS壓力放在更高權重，令這一業績成為消費風險的負面確認。", next: "看同業能否穩定，以及降價能否保護銷量／份額而不進一步壓縮利潤。", source: "[1] + [2] Reuters" },
      { tab: "DISPERSION / STOCKS", title: "事件股回吐，業績上調仍被獎勵", metric: "MRNA -23.5% · DE +6.9%", fact: "Moderna在前日臨床數據大漲後回吐23.5%；Deere上調全年淨利潤預測後上漲6.9%。", education: "事件型跳升與持續盈利變化不是同一種信號；個股反應需回到催化劑的持續性。", analysis: "市場在宏觀去風險中仍獎勵可驗證的公司級改善，因此不應把指數走弱直接寫成全面基本面惡化。", next: "繼續區分盈利／指引修正與短期主題、倉位或估值驅動的價格波動。", source: "[1] Reuters" },
      { tab: "SECTOR / OIL", title: "能源受益，消費與醫療同步承壓", metric: "Energy +0.4% · Staples -1.93%", fact: "能源為主要上漲板塊之一；必選消費、醫療和可選消費均為標普表現最弱組別。", education: "板塊防禦屬性在油價衝擊下會改變：能源受益於同一價格變數，消費卻承擔實際支出壓力。", analysis: "這是油價從跨資產變數傳導到行業相對收益的證據，而不是簡單的「防禦輪動」。", next: "觀察油價是否止升，以及消費鏈弱勢是否擴展至更多公司。", source: "[1] Reuters" },
    ] as Card[],
    watchKicker: "04 / 今天驗證甚麼", watchTitle: "讓利率、油價和同業，\n決定下一步敘事。", watchBody: "8月21日沒有重大美國數據或大型業績，因此盤前和開盤後更應關注舊主線是否繼續擴散，而非尋找新的標題。",
    watches: [
      { event: "長端利率與油價", time: "整個下一美股交易日", exposure: "估值 + 通脹 + 消費的共同開關", learn: "把收益率、油價和成長／消費的相對表現放在同一條鏈裡閱讀。", shortcut: "不要將一段期貨反彈等同於宏觀壓力解除。", positive: "10Y／30Y和油價同步回落，科技與消費停止擴大落後。", negative: "收益率、油價再上行，且成長／消費繼續承壓。" },
      { event: "Walmart同業 read-through", time: "美股盤前與開盤後", exposure: "COST、DLTR、ACI及可選消費", learn: "單一龍頭業績後，要檢查同業表現才知道衝擊是個股還是行業。", shortcut: "不要用單一EPS或單一日價格替代消費者整體結論。", positive: "同業穩定，銷量和促銷成效獲重新定價。", negative: "同業繼續走弱，說明消費者壓力由Walmart擴散。" },
      { event: "香港中期業績", time: "8月21日 · HKEX日程", exposure: "中國宏橋、中海油、紫金、中興、貝殼、東方甄選等", learn: "先看完成公告中的盈利、現金流和指引，再把結果與指數方向關聯。", shortcut: "不要把恆指早盤上漲當成任何一家公司業績已被確認。", positive: "已披露業績改善，提供宏觀之外的基本面承接。", negative: "業績分化或指引轉弱，港股早盤強勢不能延續。" },
    ] as Watch[],
    sourceKicker: "05 / 證據、時間戳與限制", sourceTitle: "事實先於敘事。", sourceBody: "美股收市和公司事實主要由Reuters核實；港股早盤來自帶時間戳的延遲Yahoo報價，業績日程來自HKEX。William本次上傳的文件是流程規範，不含今日行情事實。", sourceCut: "資料截點：2026年8月21日 11:11 HKT · 盤中資料獨立標註", archive: "歷史歸檔", archives: ["閱讀 2026.08.20", "閱讀 2026.08.19", "閱讀 2026.08.18"], footer: "內容由人工智能輔助整理，僅供市場資訊、研究及投資者教育用途；不構成個人化投資建議、證券推薦、買賣或沽空指令，也不保證任何投資回報。",
  },
  EN: {
    locale: "English research edition", switches: ["Traditional", "Simplified", "EN"], edition: "BIT DAILY / 2026.08.21", nav: ["Market thesis", "Evidence entries", "Today’s tests", "Source audit"], sourceNote: "Completed closes, delayed intraday quotes and views are shown separately.", side: "Rate relief failed;\nconsumer risk retested.",
    ledger: "THE MARKET LEDGER / 21 AUG 2026", cut: "Data cut · 11:11 HKT", strap: "U.S. close 08.20 · HK close 08.20 + intraday 08.21 · next U.S. session",
    titleA: "Rates and", titleB: "consumer risk", titleC: "returned to price setting.", hero: "The Treasury’s long-end yield relief lasted one day. Rebounding yields, oil and Walmart’s sales slowdown interrupted the rebound, putting inflation, discount rates and consumer capacity back into the market’s frame.",
    thesisLabel: "One-line thesis", thesis: "The prior rate-relief was reversed: long yields rose and Walmart did not validate consumer resilience. Until yields and oil cool, a rebound remains a condition to test—not an established trend.", auditLabel: "Yesterday → Today", audit: "Both key 20 August tests returned the adverse outcome: yields did not keep falling and Walmart’s comparable sales missed expectations.",
    snapshotKicker: "01 / Completed sessions", snapshotTitle: "The rebound broke,\nnot in volume panic.", snapshotBody: "The first three figures are completed U.S. closes on 20 August. HSI is explicitly a delayed intraday snapshot at 10:56:52 HKT on 21 August, never a close.", statNames: ["S&P 500", "NASDAQ", "DOW", "HSI · intraday"], statNotes: ["20 Aug close", "20 Aug close", "20 Aug close", "10:56 HKT / delayed quote"],
    macroKicker: "02 / Macro transmission", macroTitle: "One chain\npresses valuation and consumption.", macroBody: "10Y rose 4bp to 4.69% and 30Y 4bp to 5.24%, while WTI moved above US$87. Yields raise discount rates; oil raises both inflation and household-spending pressure.", macroLabels: ["10Y yield", "30Y yield", "WTI crude"], macroValues: ["4.69%", "5.24%", "> US$87"], macroChanges: ["+4bp", "+4bp", "fifth day higher"],
    readingMode: "Reading mode", education: "Education view", analysis: "Analysis view", reading: "How to read it", inference: "Analytical read", fact: "Fact", next: "What to test next", sourceLabel: "Source", ledgerEntry: "Ledger entry", commonShortcut: "Common shortcut", positive: "Positive confirmation", negative: "Negative confirmation", transmissionTitle: "Market transmission", transmission: [["Rates → valuation", "The previous day’s long-end relief reversed before it could establish a new pricing regime."], ["Oil → inflation / spend", "Higher fuel cost was visible both in energy leadership and a more cautious consumer read-through."], ["Earnings → dispersion", "Deere and Moderna showed why company-level evidence should not be collapsed into an index narrative."]], transmissionNote: "Yesterday’s negative confirmation is a risk condition, not a promise of a further decline.", signalsKicker: "03 / Event to price", signalsTitle: "Not every decline\nsays the same thing.", signalsBody: "Each ledger entry separates fact, price reaction, the defensible inference and its next test. A single-company move is not a market conclusion.",
    cards: [
      { tab: "MACRO / RATES", title: "Buybacks did not keep the long end down", metric: "10Y 4.69% · 30Y 5.24%", fact: "After Treasury expanded buybacks, long Treasury yields both rose 4bp the next day and the major indexes fell.", education: "An operation can support liquidity without changing inflation, supply or risk premia. Check persistence in yields before inferring valuation relief.", analysis: "The rate-relief condition from the prior day failed—the most direct macro explanation for Thursday’s price action.", next: "Only a joint pullback in yields and oil can reopen the valuation-relief case.", source: "[1] Reuters · [3] Yahoo Finance" },
      { tab: "CONSUMER / EARNINGS", title: "Walmart turned consumer concern into price", metric: "WMT -9.2% · comps +2.6%", fact: "Comparable sales grew 2.6% versus a 3.8% LSEG expectation; traffic was +1.5%, while annual sales growth guidance rose to 4–5%.", education: "Read traffic, ticket, promotion, margin and guide together. A higher annual sales guide need not cancel a near-term demand slowdown.", analysis: "Markets weighted fuel-driven consumer trade-offs and Q3 EPS pressure more heavily, making the print a negative consumer confirmation.", next: "Test whether lower prices protect unit volumes and share without deeper margin pressure.", source: "[1] + [2] Reuters" },
      { tab: "DISPERSION / STOCKS", title: "Event gains reversed; raised forecasts still won", metric: "MRNA -23.5% · DE +6.9%", fact: "Moderna gave back 23.5% after its prior clinical-data surge; Deere rose 6.9% after lifting its full-year net-income forecast.", education: "Event-driven jumps and persistent earnings changes are different signals. Return to the catalyst’s durability.", analysis: "Even in macro de-risking, verifiable company-level improvement was rewarded; index weakness is not automatically broad fundamental deterioration.", next: "Separate earnings / guide revisions from short-term thematic, positioning or valuation moves.", source: "[1] Reuters" },
      { tab: "SECTOR / OIL", title: "Energy gained; consumers and health care fell", metric: "Energy +0.4% · Staples -1.93%", fact: "Energy was among the few gainers while staples, health care and consumer discretionary were the weakest S&P groups.", education: "Defensive labels can change under an oil shock: energy benefits from the same input price that constrains consumers.", analysis: "This is cross-asset oil transmission into sector returns, not a simple defensive rotation.", next: "Watch whether oil stalls and whether consumer-chain weakness broadens.", source: "[1] Reuters" },
    ] as Card[],
    watchKicker: "04 / What tests the thesis today", watchTitle: "Let yields, oil and peers\ndecide the next narrative.", watchBody: "With no major U.S. data or large earnings expected on 21 August, pre-market and the open should test whether the existing thesis spreads—not hunt for a fresh headline.",
    watches: [
      { event: "Long yields & oil", time: "Through the next U.S. session", exposure: "Joint valuation, inflation and consumption switch", learn: "Read yields, oil and growth / consumer relative performance as one chain.", shortcut: "Do not call a short futures bounce an end to macro pressure.", positive: "10Y / 30Y and oil fall together; tech and consumer stop widening their underperformance.", negative: "Yields and oil rise again while growth / consumer remain pressured." },
      { event: "Walmart peer read-through", time: "Pre-market and open", exposure: "COST, DLTR, ACI and consumer discretionary", learn: "After a bellwether report, peers show whether the impact is company-specific or industry-wide.", shortcut: "Do not use one EPS number or one price move as the entire consumer conclusion.", positive: "Peers stabilise and volume / promotion outcomes are repriced positively.", negative: "Peers keep falling, extending consumer pressure beyond Walmart." },
      { event: "Hong Kong interim results", time: "21 Aug · HKEX diary", exposure: "China Hongqiao, CNOOC, Zijin, ZTE, Beike, East Buy and others", learn: "Read completed earnings, cash flow and guidance before connecting a result to index direction.", shortcut: "Do not treat an HSI morning rise as proof of any company’s outcome.", positive: "Released prints improve and offer fundamental support outside the macro frame.", negative: "Dispersion or softer guidance makes morning HSI strength unsustainable." },
    ] as Watch[],
    sourceKicker: "05 / Evidence, timestamps & limits", sourceTitle: "Facts before narrative.", sourceBody: "U.S. close and company facts were chiefly verified with Reuters; Hong Kong morning is a timestamped delayed Yahoo quote and the earnings diary is HKEX. William’s uploaded file is a workflow specification, not a same-day market source.", sourceCut: "Data cut: 21 Aug 2026, 11:11 HKT · intraday figures labelled separately", archive: "Historical archive", archives: ["Read 2026.08.20", "Read 2026.08.19", "Read 2026.08.18"], footer: "AI-assisted content for market information, research and investor education only. Not personalised investment advice, a securities recommendation, a buy / sell / short instruction, or a guarantee of return.",
  },
};

const sources = [
  ["Reuters · U.S. close", "https://www.reuters.com/business/us-stock-futures-muted-bond-yields-resume-uptrend-ahead-walmarts-earnings-2026-08-20/"],
  ["Reuters · Walmart Q2", "https://www.reuters.com/business/walmart-reports-rare-comparable-sales-miss-consumers-pare-back-spending-2026-08-20/"],
  ["Yahoo Finance · HSI delayed quote", "https://finance.yahoo.com/quote/%5EHSI/"],
  ["HKEX · board-meeting diary", "https://www3.hkexnews.hk/reports/bmn/ebmn_c.htm"],
  ["Schwab · market calendar", "https://www.schwab.com/learn/story/stock-market-update-open"],
];

function ResearchMark({ className = "" }: { className?: string }) {
  return <span aria-hidden="true" className={`research-mark ${className}`}><i /><i /><b /></span>;
}

type FullReportAug21Props = { language?: ReportLanguage; onLanguageChange?: (language: ReportLanguage) => void };

export default function FullReportAug21({ language: controlledLanguage, onLanguageChange }: FullReportAug21Props) {
  const [localLanguage, setLocalLanguage] = useState<ReportLanguage>(() => {
    const value = new URLSearchParams(window.location.search).get("lang");
    return value === "TW" || value === "EN" ? value : "CN";
  });
  const language = controlledLanguage ?? localLanguage;
  const [mode, setMode] = useState<Mode>("analysis");
  const text = copy[language];
  const values = ["7,641.16", "26,067.17", "52,759.21", "25,863.73"];
  const changes = ["-0.87%", "-1.00%", "-1.32%", "+0.64%"];
  const icons = [TrendingDown, TrendingDown, TrendingDown, TrendingUp];

  useEffect(() => {
    document.documentElement.lang = language === "CN" ? "zh-Hans" : language === "TW" ? "zh-Hant" : "en";
    document.title = `EQUITY / INSIGHT — ${text.edition}`;
  }, [language, text.edition]);

  function setLocale(next: ReportLanguage) {
    setLocalLanguage(next);
    onLanguageChange?.(next);
    const url = new URL(window.location.href);
    url.searchParams.set("lang", next);
    window.history.replaceState({}, "", url);
  }
  function jump(id: string) { document.getElementById(id)?.scrollIntoView({ behavior: "smooth", block: "start" }); }

  return <div className="min-h-screen bg-[#F3EFE6] text-[#16352F] lg:flex">
    <aside className="ledger-spine sticky top-0 z-30 hidden h-screen w-[236px] flex-col border-r border-[#E4DBC9] bg-[#10332D] px-6 py-7 text-[#F6F0E3] lg:flex">
      <button onClick={() => jump("overview")} className="flex items-center gap-3 text-left"><ResearchMark className="h-11 w-11" /><span><span className="block font-display text-lg leading-none">EQUITY</span><span className="mt-1 block font-mono text-[10px] tracking-[0.22em] text-[#C99A48]">INSIGHT</span></span></button>
      <div className="mt-14 border-l border-[#C99A48]/60 pl-4"><p className="font-mono text-[10px] tracking-[0.2em] text-[#C99A48]">{text.edition}</p><p className="mt-3 whitespace-pre-line font-display text-[22px] leading-tight">{text.side}</p></div>
      <nav className="mt-12 space-y-2">{text.nav.map((label: string, index: number) => <button key={label} onClick={() => jump(["overview", "signals", "watch", "sources"][index])} className="group flex w-full items-center gap-3 border-b border-white/10 py-3 text-left text-sm text-[#EAE3D5] transition hover:border-[#C99A48] hover:text-white"><span className="font-mono text-[10px] text-[#C99A48]">{String(index + 1).padStart(2, "0")}</span><span>{label}</span><ChevronRight size={14} className="ml-auto opacity-0 transition group-hover:opacity-100" /></button>)}</nav>
      <div className="mt-auto border border-white/15 bg-white/[0.04] p-4"><div className="flex items-center gap-2 text-[#C99A48]"><ShieldCheck size={15} /><span className="font-mono text-[10px] tracking-[0.16em]">SOURCE-AWARE</span></div><p className="mt-2 text-xs leading-relaxed text-[#D5CEBF]">{text.sourceNote}</p></div>
    </aside>
    <div className="min-w-0 flex-1">
          <header className="sticky top-0 z-20 border-b border-[#E4DBC9] bg-[#F3EFE6]/95 px-5 py-3 backdrop-blur sm:px-10"><div className="mx-auto flex max-w-[1500px] items-center justify-between gap-3"><button onClick={() => jump("overview")} className="flex items-center gap-2 lg:hidden"><ResearchMark className="h-7 w-7" /><span className="font-display text-sm">EQUITY / INSIGHT</span></button><div className="hidden items-center gap-3 text-[11px] font-medium tracking-[0.14em] text-[#50615B] sm:flex"><span className="status-dot" /><span>{text.locale}</span><span className="text-[#B6A997]">•</span><span>{text.edition}</span></div><div className="ml-auto flex gap-1 rounded-full border border-[#DED4C2] bg-[#FAF7F0] p-1">{(["TW", "CN", "EN"] as ReportLanguage[]).map((lang, i) => <button key={lang} onClick={() => setLocale(lang)} className={`rounded-full px-2.5 py-1 text-[10px] font-bold transition ${language === lang ? "bg-[#16352F] text-white" : "text-[#66746E] hover:text-[#16352F]"}`}>{text.switches[i]}</button>)}</div></div></header>
      <main>
        <section id="overview" className="relative min-h-[610px] overflow-hidden bg-[#102D28]"><img src={heroImage} alt="Equity Insight research desk" className="absolute inset-0 h-full w-full object-cover opacity-55" /><div className="absolute inset-0 bg-[#10332D]/70" /><div className="relative mx-auto flex min-h-[610px] max-w-[1500px] flex-col justify-end px-5 py-14 sm:px-10 lg:px-14"><div className="max-w-4xl"><div className="mb-6 flex flex-wrap items-center gap-3"><span className="ledger-rule" /><span className="font-mono text-[10px] tracking-[0.24em] text-[#E0C27B]">{text.ledger}</span><span className="border border-[#E0C27B]/45 px-2 py-1 font-mono text-[9px] tracking-[0.14em] text-[#F4E4B8]">{text.cut}</span></div><p className="font-mono text-[11px] tracking-[0.11em] text-[#D7D1C1]">{text.strap}</p><h1 className="mt-5 max-w-5xl font-display text-[46px] leading-[0.93] tracking-[-0.045em] text-[#FFF9ED] sm:text-[68px] lg:text-[80px]">{text.titleA}<br /><em className="font-normal text-[#E0C27B]">{text.titleB}</em> {text.titleC}</h1><p className="mt-7 max-w-2xl text-[15px] leading-7 text-[#E6DFD1] sm:text-[17px]">{text.hero}</p><div className="mt-9 flex flex-wrap gap-3"><button onClick={() => jump("signals")} className="group inline-flex items-center gap-2 border border-[#E0C27B] px-5 py-3 text-xs font-bold text-[#E0C27B] transition hover:bg-white/10 active:scale-[0.97]"><Layers3 size={15} />{text.nav[1]}<ArrowRight size={14} className="transition group-hover:translate-x-1" /></button><button onClick={() => jump("watch")} className="inline-flex items-center gap-2 border border-white/30 px-5 py-3 text-xs font-bold text-white transition hover:border-white hover:bg-white/10 active:scale-[0.97]"><CalendarDays size={15} />{text.nav[2]}</button></div></div></div></section>
        <section className="border-b border-[#E4DBC9] bg-[#FAF7F0] px-5 py-7 sm:px-10 lg:px-14"><div className="mx-auto grid max-w-[1500px] gap-5 xl:grid-cols-[1.15fr_2fr] xl:items-center"><div className="border-l-2 border-[#C99A48] pl-4"><p className="font-mono text-[10px] tracking-[0.2em] text-[#897A67]">{text.thesisLabel}</p><p className="mt-1 font-display text-[25px] leading-tight">{text.thesis}</p></div><div className="border-l border-[#DED4C2] pl-4"><p className="font-mono text-[10px] tracking-[0.14em] text-[#9B7739]">{text.auditLabel}</p><p className="mt-2 text-sm leading-6 text-[#68756F]">{text.audit}</p></div></div></section>
        <section className="px-5 py-14 sm:px-10 lg:px-14"><div className="mx-auto max-w-[1500px]"><div className="mb-8 flex flex-wrap items-end justify-between gap-3"><div><p className="section-kicker">{text.snapshotKicker}</p><h2 className="section-title whitespace-pre-line">{text.snapshotTitle}</h2></div><p className="max-w-lg text-sm leading-6 text-[#68756F]">{text.snapshotBody}</p></div><div className="grid border-y border-[#DCD1BE] sm:grid-cols-2 xl:grid-cols-4">{values.map((value, i) => { const Icon = icons[i]; return <article key={text.statNames[i]} className="border-b border-[#DCD1BE] py-5 sm:border-b-0 sm:px-5 sm:not-last:border-r xl:first:pl-0"><div className="flex justify-between"><p className="font-mono text-[11px] tracking-[0.12em] text-[#5D7169]">{text.statNames[i]}</p><Icon size={15} className={i === 3 ? "text-[#39785F]" : "text-[#B85B4E]"} /></div><p className="mt-3 font-mono text-[30px] font-semibold tracking-[-0.06em] text-[#14332C]">{value}</p><p className={`mt-1 font-mono text-[11px] font-bold ${i === 3 ? "text-[#39785F]" : "text-[#B85B4E]"}`}>{changes[i]}</p><p className="mt-2 font-mono text-[10px] tracking-[0.04em] text-[#7A827E]">{text.statNotes[i]}</p></article>})}</div></div></section>
        <section className="border-y border-[#E2D8C6] bg-[#EAE4D8] px-5 py-14 sm:px-10 lg:px-14"><div className="mx-auto grid max-w-[1500px] gap-8 xl:grid-cols-[1.08fr_.92fr]"><div><p className="section-kicker">{text.macroKicker}</p><h2 className="section-title mt-3 whitespace-pre-line">{text.macroTitle}</h2><p className="mt-5 max-w-2xl text-sm leading-7 text-[#68756F]">{text.macroBody}</p><div className="mt-7 grid border-l border-t border-[#D7C6A7] sm:grid-cols-3">{text.macroLabels.map((label: string, i: number) => <div key={label} className="-ml-px -mt-px border border-[#D7C6A7] bg-[#F7F1E6] p-4"><p className="font-mono text-[10px] tracking-[0.12em] text-[#68766E]">{label}</p><p className="mt-3 font-mono text-[27px] font-semibold tracking-[-0.05em] text-[#183B33]">{text.macroValues[i]}</p><p className="mt-2 font-mono text-[10px] text-[#B85B4E]">{text.macroChanges[i]}</p></div>)}</div></div><div className="bg-[#153A32] p-7 text-[#F7F0E3] sm:p-9"><p className="font-mono text-[10px] tracking-[0.18em] text-[#E0C27B]">{text.transmissionTitle}</p><div className="mt-7 space-y-5">{text.transmission.map(([title, body]: [string, string]) => <div key={title} className="border-l border-[#C99A48] pl-4"><p className="font-bold">{title}</p><p className="mt-1 text-sm leading-6 text-[#D2DDD5]">{body}</p></div>)}</div><p className="mt-7 border-t border-white/15 pt-4 text-xs leading-5 text-[#C3D0C8]"><CircleAlert className="mr-2 inline text-[#E0C27B]" size={15} />{text.transmissionNote}</p></div></div></section>
        <section id="signals" className="px-5 py-16 sm:px-10 lg:px-14"><div className="mx-auto max-w-[1500px]"><div className="grid gap-7 lg:grid-cols-[0.82fr_1.18fr] lg:items-end"><div><p className="section-kicker">{text.signalsKicker}</p><h2 className="section-title mt-3 whitespace-pre-line">{text.signalsTitle}</h2></div><div><p className="max-w-2xl text-sm leading-7 text-[#68756F]">{text.signalsBody}</p><div className="mt-5 inline-flex border border-[#D8CCB7] p-1" role="group" aria-label={text.readingMode}><button onClick={() => setMode("education")} className={`px-4 py-2 text-xs font-bold transition ${mode === "education" ? "bg-[#16382F] text-white" : "text-[#6A756F]"}`}>{text.education}</button><button onClick={() => setMode("analysis")} className={`px-4 py-2 text-xs font-bold transition ${mode === "analysis" ? "bg-[#16382F] text-white" : "text-[#6A756F]"}`}>{text.analysis}</button></div></div></div><div className="mt-9 grid border-l border-t border-[#D7C6A7] lg:grid-cols-2">{text.cards.map((card: Card, i: number) => <article key={card.title} className="research-slip relative -ml-px -mt-px flex min-h-[350px] flex-col border border-[#D7C6A7] p-6 pl-12"><span className="absolute bottom-0 left-0 top-0 flex w-7 items-center justify-center border-r border-[#C99A48] bg-[#E7DED0] px-1 text-center font-mono text-[9px] font-bold tracking-[0.08em] text-[#557067]" style={{ writingMode: "vertical-rl", textOrientation: "mixed" }}>{card.tab}</span><div className="flex justify-between"><span className="font-mono text-[10px] tracking-[0.14em] text-[#9A7230]">{String(i + 1).padStart(2, "0")} / {text.ledgerEntry.toUpperCase()}</span><ArrowUpRight size={17} className="text-[#557A6C]" /></div><h3 className="mt-5 font-display text-[30px] leading-tight">{card.title}</h3><p className="mt-2 font-mono text-[11px] font-semibold text-[#39785F]">{card.metric}</p><p className="mt-5 text-sm leading-6 text-[#68756F]"><strong className="font-mono text-[10px] tracking-[0.1em] text-[#173D35]">{text.fact.toUpperCase()} · </strong>{card.fact}</p><div className="mt-auto border-l border-[#C99A48] pl-4 pt-5"><p className="font-mono text-[10px] tracking-[0.14em] text-[#9B7739]">{mode === "education" ? text.reading : text.inference}</p><p className="mt-2 text-sm leading-6 text-[#405A51]">{mode === "education" ? card.education : card.analysis}</p><p className="mt-4 text-xs leading-5 text-[#708078]"><span className="font-mono text-[10px] font-bold tracking-[0.08em] text-[#9B7739]">{text.next.toUpperCase()} · </span>{card.next}</p><p className="mt-4 border-t border-[#DDD2C0] pt-3 font-mono text-[9px] tracking-[0.1em] text-[#8B7B62]">{text.sourceLabel.toUpperCase()} / {card.source}</p></div></article>)}</div></div></section>
        <section id="watch" className="border-y border-[#E1D7C5] bg-[#F9F5EB] px-5 py-16 sm:px-10 lg:px-14"><div className="mx-auto grid max-w-[1500px] gap-10 lg:grid-cols-[0.76fr_1.24fr]"><div><p className="section-kicker">{text.watchKicker}</p><h2 className="section-title mt-3 whitespace-pre-line">{text.watchTitle}</h2><p className="mt-5 max-w-md text-sm leading-7 text-[#68756F]">{text.watchBody}</p></div><div className="divide-y divide-[#DED3C2] border-t border-[#DED3C2]">{text.watches.map((row: Watch, i: number) => <article key={row.event} className="relative grid gap-3 py-6 pl-10 sm:grid-cols-[154px_1fr_1fr] sm:gap-6"><span className="absolute bottom-4 left-0 top-4 flex w-6 items-center justify-center border-r border-[#C99A48] bg-[#EDE5D8] px-1 text-center font-mono text-[8px] font-bold tracking-[0.08em] text-[#557067]" style={{ writingMode: "vertical-rl", textOrientation: "mixed" }}>{["RATES / OIL", "CONSUMER", "HK EARNINGS"][i]}</span><div className="border-l border-[#C99A48] pl-3"><p className="font-mono text-[10px] text-[#C99A48]">{String(i + 1).padStart(2, "0")}</p><p className="mt-1 font-display text-xl">{row.event}</p><p className="mt-2 font-mono text-[10px] font-bold text-[#4B7063]">{row.time}</p><p className="mt-1 font-mono text-[10px] text-[#799087]">{row.exposure}</p></div>{mode === "education" ? <><div><p className="font-mono text-[10px] font-bold tracking-[0.14em] text-[#39785F]">{text.reading.toUpperCase()}</p><p className="mt-2 text-sm leading-6 text-[#4F625B]">{row.learn}</p></div><div><p className="font-mono text-[10px] font-bold tracking-[0.14em] text-[#AD5E52]">{text.commonShortcut.toUpperCase()}</p><p className="mt-2 text-sm leading-6 text-[#4F625B]">{row.shortcut}</p></div></> : <><div><p className="font-mono text-[10px] font-bold tracking-[0.14em] text-[#39785F]">{text.positive.toUpperCase()}</p><p className="mt-2 text-sm leading-6 text-[#4F625B]">{row.positive}</p></div><div><p className="font-mono text-[10px] font-bold tracking-[0.14em] text-[#AD5E52]">{text.negative.toUpperCase()}</p><p className="mt-2 text-sm leading-6 text-[#4F625B]">{row.negative}</p></div></>}</article>)}</div></div></section>
        <section id="sources" className="relative overflow-hidden bg-[#10342D] px-5 py-14 text-[#F7F0E3] sm:px-10 lg:px-14"><div className="absolute left-0 top-0 h-full w-1 bg-[#C99A48]" /><div className="mx-auto grid max-w-[1500px] gap-10 lg:grid-cols-[0.9fr_1.1fr]"><div><p className="font-mono text-[10px] tracking-[0.17em] text-[#E0C27B]">{text.sourceKicker}</p><h2 className="mt-4 font-display text-[42px] leading-tight">{text.sourceTitle}</h2><p className="mt-5 max-w-lg text-sm leading-7 text-[#D3DDD6]">{text.sourceBody}</p><p className="mt-6 font-mono text-[10px] tracking-[0.12em] text-[#D9CFBB]">{text.sourceCut}</p><div className="mt-8 border-l border-[#C99A48] pl-4"><p className="font-mono text-[10px] tracking-[0.15em] text-[#E0C27B]">{text.archive}</p><div className="mt-3 flex flex-wrap gap-3">{["/archive/2026-08-20", "/archive/2026-08-19", "/archive/2026-08-18"].map((href, i) => <a key={href} href={href} className="inline-flex items-center gap-2 border border-white/20 px-3 py-2 text-xs font-bold hover:border-[#E0C27B] hover:text-[#E0C27B]"><FileArchive size={14} />{text.archives[i]}</a>)}</div></div></div><div className="grid content-start border-t border-white/15 sm:grid-cols-2">{sources.map(([label, href]) => <a key={label} href={href} target="_blank" rel="noreferrer" className="group flex items-center justify-between border-b border-white/15 py-4 text-sm text-[#E9E4D8] transition hover:text-[#E1C47D] sm:odd:pr-6 sm:even:pl-6"><span>{label}</span><ArrowUpRight size={16} className="transition group-hover:-translate-y-0.5 group-hover:translate-x-0.5" /></a>)}</div></div></section>
      </main>
      <footer className="border-t border-[#E0D5C3] bg-[#F3EFE6] px-5 py-7 sm:px-10 lg:px-14"><div className="mx-auto flex max-w-[1500px] flex-col justify-between gap-4 text-xs text-[#6D7871] sm:flex-row"><p>EQUITY / INSIGHT · {text.edition}</p><p className="max-w-xl sm:text-right">{text.footer}</p></div></footer>
    </div>
  </div>;
}
