/**
 * BIT Market Intelligence — 24 Aug 2026 weekend edition.
 * Design contract: approved BIT white / black / blue system; market direction uses green / neutral / red only.
 * Research contract: 21 Aug completed sessions are facts; 24 Aug items are weekend / next-session catalysts, never Friday price drivers.
 */
import { useState } from "react";
import { ArrowRight, CalendarDays, CheckCircle2, CircleAlert, Download, ExternalLink, Info, Printer, TrendingUp } from "lucide-react";
import usMarketData from "../../../data/2026-08-24/us_market.json";
import hkMarketData from "../../../data/2026-08-24/hk_market.json";
import thesisData from "../../../data/2026-08-24/thesis.json";
import sourcesData from "../../../data/2026-08-24/sources.json";
import analyticsData from "../../../data/2026-08-21/market_analytics.json";
import analyticsDetailData from "../../../data/2026-08-21/market_analytics_detail.json";

type Language = "TW" | "CN" | "EN";
type Section = "overview" | "us" | "hk" | "cross" | "week" | "sources";
type Mode = "education" | "analysis";
const us = usMarketData as any;
const hk = hkMarketData as any;
const thesis = thesisData as any;
const sources = (sourcesData as any).sources as any[];
const analytics = analyticsData as any;
const analyticsDetail = analyticsDetailData as any;
const base = import.meta.env.BASE_URL;

const ui: Record<Language, any> = {
  CN: {
    edition: "BIT MARKET INTELLIGENCE · WEEKEND · 2026.08.24",
    asof: "周末 as-of：2026年8月24日HKT · 美股与港股完成时段均为8月21日",
    nav: { overview: "总览", us: "美股", hk: "港股", cross: "跨市场", week: "本周关注", sources: "来源" },
    modes: { education: "投教阅读", analysis: "分析阅读" }, history: "查看 8月21日完整历史研究",
    title: "反弹出现了；收益率、油价与本周事件仍决定它能否延续。",
    thesis: "周五强于预期的服务业PMI缓解了增长骤降担忧，推动股指和市场广度反弹；但周线跌幅、长端收益率和油价仍说明估值压力没有被解决。本周的PCE／GDP、NVIDIA财报和Jackson Hole必须同时验证增长、通胀与AI资本开支能否共存。",
    summary: "研究摘要", summaryText: "周五反弹更接近由宏观数据推动的阶段性估值修复，而非新的全面风险偏好阶段。持续性需要由三项可观察条件共同支持：通胀不再上行、长端收益率不再走高，以及NVIDIA以订单和指引证明AI投入仍在转化为需求。",
    readUS: "进入美股完整研究", readHK: "进入港股完整研究", readWeek: "查看本周验证条件",
    fact: "事实", meaning: "市场含义", next: "下一验证", completed: "完成交易时段", intraday: "盘中", scheduled: "已排期", reported: "媒体报道／未获公司确认", source: "来源", positive: "正面确认", negative: "负面确认",
    usTitle: "美股：PMI减轻增长担忧，但贴现率约束尚未解除。",
    hkTitle: "港股：完成收市、周末事件与下个交易日反应必须分开。",
    crossTitle: "跨市场：只保留能影响估值或风险溢价的传导链。",
    weekTitle: "本周关注：把事件写成可验证条件，而不是新闻清单。",
    sourceTitle: "来源、权限与不确定性边界", print: "打印 / 另存PDF", disclosure: "本内容由人工智能辅助整理，按所示来源供BIT内部市场监测与研究讨论使用；不是经批准的客户沟通或推广材料。内容不构成个人化投资建议、证券推荐、买卖或沽空指令，也不保证任何投资回报。"
  },
  TW: {
    edition: "BIT MARKET INTELLIGENCE · WEEKEND · 2026.08.24",
    asof: "週末 as-of：2026年8月24日HKT · 美股與港股完成時段均為8月21日",
    nav: { overview: "總覽", us: "美股", hk: "港股", cross: "跨市場", week: "本週關注", sources: "來源" },
    modes: { education: "投教閱讀", analysis: "分析閱讀" }, history: "查看 8月21日完整歷史研究",
    title: "反彈出現了；收益率、油價與本週事件仍決定它能否延續。",
    thesis: "周五強於預期的服務業PMI緩解了增長驟降憂慮，推動股指和市場廣度反彈；但週線跌幅、長端收益率和油價仍說明估值壓力沒有被解決。本週的PCE／GDP、NVIDIA財報和Jackson Hole必須同時驗證增長、通脹與AI資本開支能否共存。",
    summary: "研究摘要", summaryText: "周五反彈更接近由宏觀數據推動的階段性估值修復，而非新的全面風險偏好階段。持續性需要由三項可觀察條件共同支持：通脹不再上行、長端收益率不再走高，以及NVIDIA以訂單和指引證明AI投入仍在轉化為需求。",
    readUS: "進入美股完整研究", readHK: "進入港股完整研究", readWeek: "查看本週驗證條件",
    fact: "事實", meaning: "市場含義", next: "下一驗證", completed: "完成交易時段", intraday: "盤中", scheduled: "已排期", reported: "媒體報道／未獲公司確認", source: "來源", positive: "正面確認", negative: "負面確認",
    usTitle: "美股：PMI減輕增長憂慮，但貼現率約束尚未解除。",
    hkTitle: "港股：完成收市、週末事件與下一交易日反應必須分開。",
    crossTitle: "跨市場：只保留能影響估值或風險溢價的傳導鏈。",
    weekTitle: "本週關注：把事件寫成可驗證條件，而不是新聞清單。",
    sourceTitle: "來源、權限與不確定性邊界", print: "列印 / 另存PDF", disclosure: "本內容由人工智能輔助整理，按所示來源供BIT內部市場監測與研究討論使用；不是經批准的客戶溝通或推廣材料。內容不構成個人化投資建議、證券推薦、買賣或沽空指令，也不保證任何投資回報。"
  },
  EN: {
    edition: "BIT MARKET INTELLIGENCE · WEEKEND · 2026.08.24",
    asof: "Weekend as-of: 24 Aug 2026 HKT · completed U.S. and Hong Kong sessions are both 21 Aug",
    nav: { overview: "Overview", us: "U.S. Market", hk: "Hong Kong", cross: "Cross-market", week: "This Week", sources: "Sources" },
    modes: { education: "Education reading", analysis: "Analysis reading" }, history: "View full 21 Aug historical research",
    title: "The rebound arrived; yields, oil and this week’s events still decide whether it lasts.",
    thesis: "A stronger services PMI eased fears of a growth air pocket and lifted indices and breadth on Friday. Weekly losses, long yields and oil still say the valuation constraint is unresolved. PCE/GDP, Nvidia and Jackson Hole must now test whether growth, inflation and AI capex can coexist.",
    summary: "Research summary", summaryText: "Friday’s rebound is better framed as a data-led valuation repair than a new broad risk-on regime. Persistence requires three observable conditions: inflation does not reaccelerate, long yields do not move higher, and Nvidia demonstrates through orders and guidance that AI investment is still converting into demand.",
    readUS: "Read full U.S. research", readHK: "Read full Hong Kong research", readWeek: "Read this week’s tests",
    fact: "Fact", meaning: "What it means", next: "Next validation", completed: "Completed session", intraday: "Intraday", scheduled: "Scheduled", reported: "Reported / not company-confirmed", source: "Source", positive: "Positive confirmation", negative: "Negative confirmation",
    usTitle: "U.S.: PMI eased growth fears; the discount-rate constraint remains.",
    hkTitle: "Hong Kong: completed close, weekend event and next-session reaction must stay separate.",
    crossTitle: "Cross-market: retain only transmission paths that can change valuation or risk premium.",
    weekTitle: "This week: convert events into test conditions—not a news list.",
    sourceTitle: "Sources, entitlement and uncertainty boundary", print: "Print / Save PDF", disclosure: "AI-assisted content, based on the sources shown, for BIT internal market monitoring and research discussion. It is not approved client communication or promotional material. It is not personalised investment advice, a securities recommendation, a buy/sell/short instruction or a guarantee of return."
  }
};

const depth: Record<Language, Record<Mode, { title: string; body: string; prompts: string[] }>> = {
  CN: {
    education: { title: "怎样读这份周末报告", body: "先区分完成收市、周末变量和本周日程。再把价格反应放回增长、通胀、收益率和盈利四个问题里，而不是把每条新闻当作交易结论。", prompts: ["PMI强不等于降息或股市必涨：它同时会影响增长预期和利率。", "NVIDIA财报是AI链的基本面检查点，不是所有科技股的自动结论。", "阿里配售属于周末后事件；必须等待下个港股交易日的价格与成交确认。"] },
    analysis: { title: "当前研究判断与失效条件", body: "基准判断是周五的宏观喘息尚未推翻长端收益率、油价和周线仓位的压力。只有宏观数据、利率和NVIDIA指引共同改善，才足以把反弹从修复提升为更稳固的风险偏好。", prompts: ["若PCE／GDP组合推高长端收益率，周五反弹的估值基础会被削弱。", "若NVIDIA需求／指引稳健且收益率不再上行，AI硬件链才获得基本面确认。", "若油价或Hormuz风险溢价上升，通胀与全球成长估值的压力会重新同步出现。"] }
  },
  TW: {
    education: { title: "怎樣讀這份週末報告", body: "先區分完成收市、週末變量和本週日程。再把價格反應放回增長、通脹、收益率和盈利四個問題裡，而不是把每條新聞當作交易結論。", prompts: ["PMI強不等於減息或股市必升：它同時會影響增長預期和利率。", "NVIDIA財報是AI鏈的基本面檢查點，不是所有科技股的自動結論。", "阿里配售屬於週末後事件；必須等待下一個港股交易日的價格與成交確認。"] },
    analysis: { title: "當前研究判斷與失效條件", body: "基準判斷是周五的宏觀喘息尚未推翻長端收益率、油價和週線倉位的壓力。只有宏觀數據、利率和NVIDIA指引共同改善，才足以把反彈從修復提升為更穩固的風險偏好。", prompts: ["若PCE／GDP組合推高長端收益率，周五反彈的估值基礎會被削弱。", "若NVIDIA需求／指引穩健且收益率不再上行，AI硬件鏈才獲得基本面確認。", "若油價或Hormuz風險溢價上升，通脹與全球成長估值的壓力會重新同步出現。"] }
  },
  EN: {
    education: { title: "How to read this weekend report", body: "Separate completed closes, weekend variables and this week’s calendar. Then place price action back into four questions—growth, inflation, yields and earnings—instead of treating each headline as a trading conclusion.", prompts: ["A strong PMI does not automatically mean rate cuts or rising equities; it changes both growth and rate expectations.", "Nvidia earnings are a fundamental check for the AI chain, not an automatic conclusion for all technology.", "Alibaba’s placement is a post-weekend event; wait for next-session price and volume confirmation."] },
    analysis: { title: "Current thesis and invalidation conditions", body: "The base case is that Friday’s macro relief did not overturn pressure from long yields, oil and weak weekly positioning. A durable upgrade needs macro data, rates and Nvidia guidance to improve together.", prompts: ["If the PCE/GDP mix lifts long yields, the valuation basis for Friday’s rebound weakens.", "If Nvidia demand/guidance is firm while yields stop rising, AI hardware receives fundamental confirmation.", "If oil or Hormuz risk premium rises, inflation and global growth-duration valuation pressure can re-synchronise."] }
  }
};

const color = (value: number) => value > 0.1 ? "#10B99A" : value < -0.1 ? "#FF6A1A" : "#E5E7EB";
const pct = (value: number) => `${value > 0 ? "+" : ""}${value.toFixed(2)}%`;

export default function WeekendAug24Full() {
  const params = new URLSearchParams(window.location.search);
  const [language, setLanguage] = useState<Language>(() => (params.get("lang") === "TW" || params.get("lang") === "EN" ? params.get("lang") as Language : "CN"));
  const [section, setSection] = useState<Section>(() => (["us", "hk", "cross", "week", "sources"].includes(params.get("market") || "") ? params.get("market") as Section : "overview"));
  const [mode, setMode] = useState<Mode>("analysis");
  const [heatmapWindow, setHeatmapWindow] = useState<"oneDay" | "fiveDay" | "twentyDay">("oneDay");
  const t = ui[language];
  const d = depth[language][mode];
  const navigate = (next: Section, nextLanguage = language) => { const url = new URL(window.location.href); url.searchParams.set("market", next); url.searchParams.set("lang", nextLanguage); window.history.replaceState({}, "", url); setSection(next); setLanguage(nextLanguage); window.scrollTo({ top: 0, behavior: "smooth" }); };
  const macro = language === "EN" ? [
    ["Flash services PMI", "56.8", "Composite 56.0; growth relief, not a rate-risk resolution."], ["10Y / 30Y Treasury", "4.73% / 5.266%", "Long-end discount-rate pressure remains."], ["Brent", "US$94.39", "+6.39% for the week; oil remains an inflation-risk channel."], ["Breadth / volume", "NYSE 1.68:1", "Turnover below 20-day average; participation improved, persistence not proven."]
  ] : language === "TW" ? [
    ["Flash服務業PMI", "56.8", "綜合PMI 56.0；增長喘息，不等於利率風險解除。"], ["10Y / 30Y美債", "4.73% / 5.266%", "長端貼現率壓力仍在。"], ["Brent", "US$94.39", "全週+6.39%；油價仍是通脹風險渠道。"], ["廣度 / 成交", "NYSE 1.68:1", "成交低於20日平均；參與改善但持續性未證。"]
  ] : [
    ["Flash服务业PMI", "56.8", "综合PMI 56.0；增长喘息，不等于利率风险解除。"], ["10Y / 30Y美债", "4.73% / 5.266%", "长端贴现率压力仍在。"], ["Brent", "US$94.39", "全周+6.39%；油价仍是通胀风险渠道。"], ["广度 / 成交", "NYSE 1.68:1", "成交低于20日平均；参与改善但持续性未证。"]
  ];
  const industry = language === "EN" ? [
    ["Nvidia FY27 Q2", "Officially scheduled for 26 Aug after the U.S. close. Read data-centre demand, Blackwell/Rubin cadence and guidance—not the headline alone.", "Confirmed event"], ["Server-price report", "A Bloomberg-sourced report says some AI-server systems could rise more than 15% in 2027. Reuters could not immediately verify it and Nvidia had not commented.", "Reported / unconfirmed"], ["Samsung returns", "Samsung expects 2026 shareholder returns of 90–110tn won; it is a memory/semiconductor capital-allocation signal, not a direct Nvidia forecast.", "Confirmed context"]
  ] : language === "TW" ? [
    ["NVIDIA FY27 Q2", "官方已排期於8月26日美股收市後公布。應讀資料中心需求、Blackwell／Rubin節奏與指引，而非只看標題。", "已確認事件"], ["伺服器加價報道", "Bloomberg來源報道稱部分AI伺服器系統2027年可能加價逾15%；Reuters未能即時核實，NVIDIA未有回應。", "媒體報道／未確認"], ["Samsung股東回報", "Samsung預期2026年股東回報90–110tn韓圜；屬記憶體／半導體資本配置訊號，非對NVIDIA的直接預測。", "已確認背景"]
  ] : [
    ["NVIDIA FY27 Q2", "官方已排期于8月26日美股收市后公布。应读数据中心需求、Blackwell／Rubin节奏与指引，而非只看标题。", "已确认事件"], ["服务器涨价报道", "Bloomberg来源报道称部分AI服务器系统2027年可能涨价逾15%；Reuters未能即时核实，NVIDIA未有回应。", "媒体报道／未确认"], ["Samsung股东回报", "Samsung预计2026年股东回报90–110tn韩元；属存储／半导体资本配置信号，非对NVIDIA的直接预测。", "已确认背景"]
  ];
  const weeklyRows = language === "EN" ? thesis.this_week : language === "TW" ? [
    { event: "BEA GDP第二次估值與7月PCE", when: "8月26日 08:30 ET／8月26日 20:30 HKT", explanation: "增長與通脹必須一併閱讀；同一份數據會改變政策利率與估值框架。", positive: "通脹沒有再加速，且活動數據仍符合軟著陸敘事。", negative: "核心通脹偏高，足以令長端收益率壓力維持高位。" },
    { event: "NVIDIA FY27 Q2業績", when: "8月26日 14:00 PT／8月27日 05:00 HKT", explanation: "這是AI基礎設施鏈最直接的基本面測試，不可外推為全部科技股的替代指標。", positive: "資料中心需求和前瞻指引支持AI基建可見度。", negative: "供應、客戶資本開支或需求釋放的保守論述重啟AI硬件去風險化。" },
    { event: "Jackson Hole年會", when: "8月27日至29日", explanation: "應把已確認的政策溝通與演講後的市場解讀分開。", positive: "溝通降低政策與長端利率不確定性。", negative: "通脹、財政或政策框架不確定性抬高貼現率壓力。" },
    { event: "伊朗制裁／Hormuz與貿易風險", when: "週末至週初催化劑", explanation: "此項屬風險溢價監測，而非確定性市場方向判斷。", positive: "油價及航運風險溢價持續回落。", negative: "制裁、航運中斷或關稅升級再次推高油價及通脹風險。" }
  ] : [
    { event: "BEA GDP第二次估值与7月PCE", when: "8月26日 08:30 ET／8月26日 20:30 HKT", explanation: "增长与通胀必须一并阅读；同一份数据会改变政策利率与估值框架。", positive: "通胀没有再加速，且活动数据仍符合软着陆叙事。", negative: "核心通胀偏高，足以令长端收益率压力维持高位。" },
    { event: "NVIDIA FY27 Q2业绩", when: "8月26日 14:00 PT／8月27日 05:00 HKT", explanation: "这是AI基础设施链最直接的基本面测试，不可外推为全部科技股的替代指标。", positive: "数据中心需求和前瞻指引支持AI基建可见度。", negative: "供应、客户资本开支或需求释放的保守论述重启AI硬件去风险化。" },
    { event: "Jackson Hole年会", when: "8月27日至29日", explanation: "应把已确认的政策沟通与演讲后的市场解读分开。", positive: "沟通降低政策与长端利率不确定性。", negative: "通胀、财政或政策框架不确定性抬高贴现率压力。" },
    { event: "伊朗制裁／Hormuz与贸易风险", when: "周末至周初催化剂", explanation: "此项属风险溢价监测，而非确定性市场方向判断。", positive: "油价及航运风险溢价持续回落。", negative: "制裁、航运中断或关税升级再次推高油价及通胀风险。" }
  ];
  const sectorName = (label: string) => language === "EN" ? label : ({ Materials: language === "TW" ? "原物料" : "材料", "Health care": language === "TW" ? "醫療保健" : "医疗保健", Financials: "金融", Energy: "能源", Utilities: language === "TW" ? "公用事業" : "公用事业" } as Record<string, string>)[label] || label;
  const companyText: Record<Language, Record<string, { event: string; meaning: string; watch: string }>> = {
    EN: {
      NVDA: { event: "FY27 Q2 results are officially scheduled for 26 Aug, 14:00 PT.", meaning: "The earnings release is the direct fundamental check for AI infrastructure demand.", watch: "Data-centre demand, delivery cadence, customer capex and forward guidance." },
      ROST: { event: "Ross Stores beat quarterly expectations and raised its annual profit forecast.", meaning: "It is a company-specific consumer-resilience signal, not proof for the whole retail complex.", watch: "Whether resilience broadens beyond a single value retailer." },
      "HOOD / COIN / MSTR": { event: "Crypto-linked equities advanced with Bitcoin during Friday’s alternative-asset rebound.", meaning: "They are high-beta read-throughs for crypto risk appetite, not a substitute for adoption or regulatory evidence.", watch: "Price, volume and policy confirmation rather than one-session beta." }
    },
    TW: {
      NVDA: { event: "FY27 Q2業績已官方排期於8月26日14:00 PT公布。", meaning: "這是AI基礎設施需求的直接基本面檢查點。", watch: "資料中心需求、交付節奏、客戶資本開支及前瞻指引。" },
      ROST: { event: "Ross Stores季度業績勝預期，並上調全年盈利預測。", meaning: "這是公司層面的消費韌性訊號，並非整個零售板塊的證明。", watch: "消費韌性能否擴散至單一價值零售商以外。" },
      "HOOD / COIN / MSTR": { event: "加密相關股票隨比特幣於周五替代資產反彈中上升。", meaning: "它們是加密風險偏好的高beta read-through，不能取代採用或監管的基本面證據。", watch: "觀察價格、成交和政策確認，而非單日beta。" }
    },
    CN: {
      NVDA: { event: "FY27 Q2业绩已官方排期于8月26日14:00 PT公布。", meaning: "这是AI基础设施需求的直接基本面检查点。", watch: "数据中心需求、交付节奏、客户资本开支及前瞻指引。" },
      ROST: { event: "Ross Stores季度业绩胜预期，并上调全年盈利预测。", meaning: "这是公司层面的消费韧性信号，并非整个零售板块的证明。", watch: "消费韧性能否扩散至单一价值零售商以外。" },
      "HOOD / COIN / MSTR": { event: "加密相关股票随比特币于周五替代资产反弹中上涨。", meaning: "它们是加密风险偏好的高beta read-through，不能取代采用或监管的基本面证据。", watch: "观察价格、成交和政策确认，而非单日beta。" }
    }
  };
  const heatmapLabel = (label: string) => language === "EN" ? label : ({
    "Materials": language === "TW" ? "原物料" : "材料", "Health Care": language === "TW" ? "醫療保健" : "医疗保健", "Consumer Discretionary": language === "TW" ? "非必需消費" : "非必需消费", "Financials": "金融", "Consumer Staples": language === "TW" ? "必需消費" : "必需消费", "Communication Services": language === "TW" ? "通訊服務" : "通信服务", "Industrials": language === "TW" ? "工業" : "工业", "Technology": language === "TW" ? "科技" : "科技", "Real Estate": language === "TW" ? "房地產" : "房地产", "Energy": "能源", "Utilities": language === "TW" ? "公用事業" : "公用事业"
  } as Record<string, string>)[label] || label;
  const exportHeatmap = () => {
    const label = heatmapWindow === "oneDay" ? "1D" : heatmapWindow === "fiveDay" ? "5D" : "20D";
    const cells = analyticsDetail.sector_heatmap.map((row: any, index: number) => {
      const value = row[heatmapWindow]; const x = (index % 3) * 360; const y = Math.floor(index / 3) * 130;
      return `<rect x="${x}" y="${y}" width="348" height="118" rx="12" fill="${color(value)}"/><text x="${x + 18}" y="${y + 40}" font-family="Arial" font-size="16" font-weight="700" fill="#0A0D14">${row.symbol} · ${row.label}</text><text x="${x + 18}" y="${y + 86}" font-family="Arial" font-size="30" font-weight="700" fill="#0A0D14">${pct(value)}</text>`;
    }).join("");
    const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1080" height="580" viewBox="0 0 1080 580"><rect width="1080" height="580" fill="#ffffff"/><text x="24" y="34" font-family="Arial" font-size="18" font-weight="700" fill="#0040FF">BIT MARKET INTELLIGENCE · SECTOR HEATMAP · ${label}</text><text x="24" y="558" font-family="Arial" font-size="12" fill="#59657A">As of U.S. close 21 Aug 2026 · Select Sector SPDR ETF adjusted-close proxy · green positive / grey neutral / orange-red negative</text>${cells}</svg>`;
    const blob = new Blob([svg], { type: "image/svg+xml" }); const url = URL.createObjectURL(blob); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `bit-sector-heatmap-2026-08-21-${label}.svg`; anchor.click(); URL.revokeObjectURL(url);
  };

  const Overview = () => <main className="mx-auto max-w-[1200px] px-5 py-10 sm:px-10 lg:px-[var(--layout-padding)]">
    <section className="border-b border-[#E4E6EA] pb-10"><p className="section-kicker">WEEKEND / FRIDAY CLOSE → THIS WEEK</p><h1 className="section-title mt-3 max-w-5xl">{t.title}</h1><p className="mt-6 max-w-4xl text-[17px] leading-8 text-[#59657A]">{t.thesis}</p><div className="mt-8 border-l-2 border-[#0040FF] bg-[#F5F7FA] p-5"><p className="font-mono text-[10px] font-bold tracking-[.14em] text-[#0040FF]">{t.summary.toUpperCase()}</p><p className="mt-3 max-w-4xl text-[15px] leading-7 text-[#0A0D14]">{t.summaryText}</p></div></section>
    <section className="grid gap-5 py-10 lg:grid-cols-2"><Card label="U.S. MARKET / 21 AUG CLOSE" value="Dow +0.98% · S&P +0.43% · Nasdaq +0.44%" body={`${us.weekly_change_pct["S&P 500"]}% S&P weekly · ${us.weekly_change_pct.Nasdaq}% Nasdaq weekly`} action={t.readUS} onClick={() => navigate("us")} /><Card label="HONG KONG / 21 AUG CLOSE" value={`HSI ${hk.completed_session.HSI.toLocaleString()}`} body={`${t.asof} · no weekend close is implied`} action={t.readHK} onClick={() => navigate("hk")} secondary /></section>
    <section className="rounded-[12px] bg-[#0A0D14] p-7 text-white"><p className="font-mono text-[10px] tracking-[.16em] text-[#478DFF]">RESEARCH POSITIONING / 21 AUG → THIS WEEK</p><p className="mt-4 max-w-4xl text-[16px] leading-7 text-[#EDF1F7]">{language === "EN" ? "Friday’s price action improved breadth, but it did not resolve the rates–oil–AI valuation triangle. The weekly agenda deliberately tests all three legs rather than extrapolating a single session." : language === "TW" ? "周五價格反應改善了廣度，但未解決利率—油價—AI估值三角。本週日程刻意同時檢驗三條腿，而非由單一交易日外推。" : "周五价格反应改善了广度，但未解决利率—油价—AI估值三角。本周日程刻意同时检验三条腿，而非由单一交易日外推。"}</p><button onClick={() => navigate("week")} className="bit-action mt-6 inline-flex items-center gap-2 border border-[#478DFF] px-4 py-2 text-xs font-bold"><CalendarDays size={14}/>{t.readWeek}<ArrowRight size={14}/></button></section>
    <ReadingLayer title={d.title} body={d.body} prompts={d.prompts} mode={mode} setMode={setMode} labels={t.modes} />
  </main>;

  const US = () => <main className="pb-12"><Hero kicker="U.S. MARKET / COMPLETED 21 AUG" title={t.usTitle} body={language === "EN" ? "The Friday move must be read together with weekly losses, long-end yields and the oil premium—not as an isolated signal." : language === "TW" ? "周五走勢必須與週線跌幅、長端收益率和油價風險溢價一併閱讀，而不是孤立訊號。" : "周五走势必须与周线跌幅、长端收益率和油价风险溢价一并阅读，而不是孤立信号。"}/>
    <section className="border-y border-[#E4E6EA] bg-[#F5F7FA] px-5 py-8 sm:px-10 lg:px-[var(--layout-padding)]"><div className="mx-auto max-w-[1200px]"><p className="section-kicker">{t.completed}</p><div className="mt-5 grid border-l border-t border-[#E4E6EA] md:grid-cols-3">{Object.entries(us.index_close).map(([name, row]: [string, any]) => <article key={name} className="-ml-px -mt-px border border-[#E4E6EA] bg-white p-6"><p className="font-mono text-[10px] tracking-[.14em] text-[#59657A]">{name}</p><p className="mt-4 font-mono text-3xl font-semibold">{row.value.toLocaleString()}</p><p className="mt-2 font-mono text-sm text-[#17733B]">{pct(row.change_pct)}</p></article>)}</div></div></section>
    <section className="mx-auto max-w-[1200px] px-5 py-12 sm:px-10 lg:px-[var(--layout-padding)]"><p className="section-kicker">{language === "EN" ? "MACRO / MARKET DRIVERS" : language === "TW" ? "宏觀 / 市場驅動" : "宏观 / 市场驱动"}</p><div className="mt-6 grid border-l border-t border-[#E4E6EA] lg:grid-cols-4">{macro.map(([label, value, body]) => <article key={label} className="-ml-px -mt-px border border-[#E4E6EA] bg-white p-6"><p className="font-mono text-[10px] tracking-[.12em] text-[#59657A]">{label}</p><p className="mt-4 font-mono text-2xl font-semibold">{value}</p><p className="mt-4 text-sm leading-6 text-[#59657A]">{body}</p></article>)}</div></section>
    <section className="bg-[#0A0D14] px-5 py-12 text-white sm:px-10 lg:px-[var(--layout-padding)]"><div className="mx-auto max-w-[1200px]"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="font-mono text-[10px] tracking-[.16em] text-[#478DFF]">{language === "EN" ? "SECTOR HEATMAP / COMPLETED 21 AUG" : language === "TW" ? "板塊熱力圖 / 8月21日完成時段" : "板块热力图 / 8月21日完成时段"}</p><p className="mt-3 text-sm text-[#BFC7D6]">{language === "EN" ? "Hover a tile to compare 1D / 5D / 20D. Export creates a shareable SVG research artifact." : language === "TW" ? "懸停格子比較1D／5D／20D；匯出會建立可分享的SVG研究檔案。" : "悬停格子比较1D／5D／20D；导出会建立可分享的SVG研究文件。"}</p></div><div className="flex flex-wrap gap-2">{(["oneDay", "fiveDay", "twentyDay"] as const).map((window) => <button key={window} onClick={() => setHeatmapWindow(window)} className={`bit-action border px-3 py-2 font-mono text-[10px] font-bold ${heatmapWindow === window ? "border-[#478DFF] bg-[#0040FF] text-white" : "border-white/20 text-[#BFC7D6]"}`}>{window === "oneDay" ? "1D" : window === "fiveDay" ? "5D" : "20D"}</button>)}<button onClick={exportHeatmap} className="bit-action inline-flex items-center gap-2 border border-[#478DFF] px-3 py-2 font-mono text-[10px] font-bold text-[#BFD3FF]"><Download size={13}/>{language === "EN" ? "EXPORT" : language === "TW" ? "匯出" : "导出"}</button></div></div><div className="mt-6 grid gap-2 sm:grid-cols-3">{analyticsDetail.sector_heatmap.map((item: any) => <div key={item.symbol} title={`1D ${pct(item.oneDay)} · 5D ${pct(item.fiveDay)} · 20D ${pct(item.twentyDay)}`} className="min-h-28 rounded-[8px] p-4" style={{ background: color(item[heatmapWindow]), color: "#0A0D14" }}><p className="font-mono text-[10px] font-bold tracking-[.1em]">{item.symbol} · {heatmapLabel(item.label)}</p><p className="mt-4 font-mono text-2xl">{pct(item[heatmapWindow])}</p></div>)}</div><p className="mt-5 text-xs text-[#B0B9C9]">{language === "EN" ? "Market direction colour only: green positive, grey neutral, orange-red negative. BIT Blue is not a performance colour." : language === "TW" ? "市場方向色僅代表收益：綠色正向、灰色中性、橙紅負向。BIT Blue不代表表現。" : "市场方向色仅代表收益：绿色正向、灰色中性、橙红负向。BIT Blue不代表表现。"}</p></div></section>
    <section className="mx-auto max-w-[1200px] px-5 py-12 sm:px-10 lg:px-[var(--layout-padding)]"><p className="section-kicker">{language === "EN" ? "STOCKS / INDUSTRY CHAIN" : language === "TW" ? "個股 / 產業鏈" : "个股 / 产业链"}</p><div className="mt-6 grid gap-5 lg:grid-cols-3">{us.companies.map((row: any) => <EvidenceCard key={row.ticker} title={`${row.ticker} · ${row.reaction}`} fact={companyText[language][row.ticker].event} implication={companyText[language][row.ticker].meaning} watch={companyText[language][row.ticker].watch} t={t}/>)}</div></section>
    <section className="bg-[#F5F7FA] px-5 py-12 sm:px-10 lg:px-[var(--layout-padding)]"><div className="mx-auto grid max-w-[1200px] gap-5 lg:grid-cols-2"><article className="rounded-[12px] border border-[#E4E6EA] bg-white p-7"><p className="section-kicker">U.S. BREADTH PROXY / 21 AUG</p><div className="mt-6 grid grid-cols-2 gap-4"><Metric label="1D" value={`${analytics.latest.daily_breadth_pct}%`}/><Metric label="5D" value={`${analytics.latest.five_day_breadth_pct}%`}/><Metric label="20D" value={`${analytics.latest.twenty_day_breadth_pct}%`}/><Metric label="SPY 5D" value={`${analytics.latest.spy_five_day_return_pct}%`}/></div><p className="mt-6 text-xs leading-5 text-[#59657A]">{language === "EN" ? "11 Select Sector SPDR ETF adjusted-close proxy; not exchange constituent advance/decline breadth." : language === "TW" ? "11個Select Sector SPDR ETF adjusted-close代理；非交易所成分股漲跌家數。" : "11个Select Sector SPDR ETF adjusted-close代理；非交易所成分股涨跌家数。"}</p></article><article className="rounded-[12px] bg-[#0A0D14] p-7 text-white"><p className="font-mono text-[10px] tracking-[.16em] text-[#478DFF]">WHAT FRIDAY DID NOT PROVE</p><p className="mt-5 text-[16px] leading-8 text-[#EDF1F7]">{language === "EN" ? "Improved breadth and a stronger PMI do not by themselves invalidate elevated long yields, oil-driven inflation risk or the weekly AI hardware drawdown. This is why the report treats PCE/GDP, Nvidia and Jackson Hole as linked tests." : language === "TW" ? "改善的廣度和較強PMI本身並不能否定高長端收益率、油價推動的通脹風險或AI硬件週線回撤。因此本報告把PCE／GDP、NVIDIA和Jackson Hole視為相連測試。" : "改善的广度和较强PMI本身并不能否定高长端收益率、油价推动的通胀风险或AI硬件周线回撤。因此本报告把PCE／GDP、NVIDIA和Jackson Hole视为相连测试。"}</p></article></div></section>
  </main>;

  const HK = () => <main className="pb-12"><Hero kicker="HONG KONG / COMPLETED 21 AUG + WEEKEND CATALYSTS" title={t.hkTitle} body={language === "EN" ? "Friday’s completed HSI close is the fact boundary. The Alibaba placement and any Monday price reaction are a later session variable, not a retrospective Friday driver." : language === "TW" ? "周五完成的恆指收市是事實邊界。阿里配售及任何周一價格反應是後續交易日變量，不可回溯寫成周五驅動。" : "周五完成的恒指收市是事实边界。阿里配售及任何周一价格反应是后续交易日变量，不可回溯写成周五驱动。"}/>
    <section className="bg-[#F5F7FA] px-5 py-10 sm:px-10 lg:px-[var(--layout-padding)]"><div className="mx-auto grid max-w-[1200px] gap-5 lg:grid-cols-2"><article className="rounded-[12px] border border-[#E4E6EA] bg-white p-7"><p className="section-kicker">{t.completed}</p><p className="mt-5 font-mono text-5xl font-semibold">{hk.completed_session.HSI.toLocaleString()}</p><p className="mt-4 font-mono text-xs text-[#17733B]">{hk.completed_session.date} · HSI close</p><p className="mt-5 text-sm leading-7 text-[#59657A]">Open {hk.completed_session.open.toLocaleString()} · High {hk.completed_session.high.toLocaleString()} · Low {hk.completed_session.low.toLocaleString()}</p></article><EvidenceCard title="Alibaba / 9988 HK" fact={language === "EN" ? "Reuters reports a HK$80bn placement at HK$112.70, 8.4% below the prior close, to fund AI-related development; early Monday trading was -8%." : language === "TW" ? "Reuters報道HK$800億配售，定價HK$112.70、較前收市折讓8.4%，用於AI相關發展；周一早段跌8%。" : "Reuters报道HK$800亿配售，定价HK$112.70、较前收市折让8.4%，用于AI相关发展；周一早段跌8%。"} implication={language === "EN" ? "AI capex and dilution / funding cost are two simultaneous signals." : language === "TW" ? "AI資本開支與稀釋／融資成本是兩個同步訊號。" : "AI资本开支与稀释／融资成本是两个同步信号。"} watch={language === "EN" ? "Treat as next-session evidence only; observe price, volume and peer read-through." : language === "TW" ? "只作下個交易日證據；觀察價格、成交與同業read-through。" : "只作下个交易日证据；观察价格、成交与同业read-through。"} t={t} badge={t.scheduled}/></div></section>
    <section className="mx-auto max-w-[1200px] px-5 py-12 sm:px-10 lg:px-[var(--layout-padding)]"><p className="section-kicker">HONG KONG EVIDENCE DISCIPLINE</p><div className="grid gap-5 lg:grid-cols-3"><SimpleCard title={language === "EN" ? "Completed close" : language === "TW" ? "完成收市" : "完成收市"} body={language === "EN" ? "Use 21 Aug HSI only as completed market fact. There is no 24 Aug Hong Kong close." : language === "TW" ? "只把8月21日恆指作完成市場事實。8月24日沒有港股收市。" : "只把8月21日恒指作完成市场事实。8月24日没有港股收市。"}/><SimpleCard title={language === "EN" ? "Weekend variable" : language === "TW" ? "週末變量" : "周末变量"} body={language === "EN" ? "Alibaba’s placement is a new financing/capex variable; it does not rewrite Friday’s session." : language === "TW" ? "阿里配售是新的融資／capex變量；不能改寫周五交易時段。" : "阿里配售是新的融资／capex变量；不能改写周五交易时段。"}/><SimpleCard title={language === "EN" ? "Next validation" : language === "TW" ? "下一驗證" : "下一验证"} body={language === "EN" ? "Watch whether dilution, AI capex and broad liquidity produce a single or divergent read-through in 9988 and peers." : language === "TW" ? "看稀釋、AI capex和整體流動性在9988及同業產生單一還是分歧的read-through。" : "看稀释、AI capex和整体流动性在9988及同业产生单一还是分歧的read-through。"}/></div></section>
  </main>;

  const Cross = () => <main className="pb-12"><Hero kicker="CROSS-MARKET / CONDITIONAL READ-THROUGH" title={t.crossTitle} body={language === "EN" ? "The cross-market section is intentionally narrow: yields and oil can change global growth-duration valuation and inflation risk; they do not automatically explain every Hong Kong price move." : language === "TW" ? "跨市場區刻意收窄：收益率和油價可改變全球成長久期估值與通脹風險；它們不會自動解釋每一個港股走勢。" : "跨市场区刻意收窄：收益率和油价可改变全球成长久期估值与通胀风险；它们不会自动解释每一个港股走势。"}/>
    <section className="mx-auto max-w-[1200px] px-5 py-12 sm:px-10 lg:px-[var(--layout-padding)]"><div className="rounded-[12px] bg-[#0A0D14] p-7 text-white"><p className="font-mono text-[10px] tracking-[.16em] text-[#478DFF]">DRIVER CHAIN / CONDITIONAL</p><div className="mt-7 grid border-l border-t border-white/15 md:grid-cols-4">{(language === "EN" ? ["Long yields / oil", "Discount rate and inflation premium", "Global growth-duration / AI valuation", "U.S. and Hong Kong price confirmation"] : language === "TW" ? ["長端收益率 / 油價", "貼現率與通脹風險溢價", "全球成長久期 / AI估值", "美股與港股價格確認"] : ["长端收益率 / 油价", "贴现率与通胀风险溢价", "全球成长久期 / AI估值", "美股与港股价格确认"]).map((label, i) => <div key={label} className="-ml-px -mt-px min-h-32 border border-white/15 p-5"><p className="font-mono text-[10px] text-[#478DFF]">0{i + 1}</p><p className="mt-4 text-sm leading-6">{label}</p></div>)}</div><p className="mt-6 text-sm leading-7 text-[#BFC7D6]">{language === "EN" ? "Status: UNRESOLVED. The chain is a monitoring framework, not a causal claim. Require a completed local session and company/sector evidence before treating it as confirmation." : language === "TW" ? "狀態：UNRESOLVED。此鏈條是監測框架，非因果結論。在視為確認前，需要完成的本地交易時段及公司／板塊證據。" : "状态：UNRESOLVED。此链条是监测框架，非因果结论。在视为确认前，需要完成的本地交易时段及公司／板块证据。"}</p></div></section>
    <section className="bg-[#F5F7FA] px-5 py-12 sm:px-10 lg:px-[var(--layout-padding)]"><div className="mx-auto grid max-w-[1200px] gap-5 lg:grid-cols-3"><Scenario title={language === "EN" ? "Positive" : language === "TW" ? "正面情景" : "正面情景"} body={language === "EN" ? "PCE/GDP stay compatible with easing inflation risk, yields stabilise and Nvidia guidance supports AI demand." : language === "TW" ? "PCE／GDP與通脹風險降溫兼容、收益率穩定且NVIDIA指引支持AI需求。" : "PCE／GDP与通胀风险降温兼容、收益率稳定且NVIDIA指引支持AI需求。"} tone="good"/><Scenario title={language === "EN" ? "Base" : language === "TW" ? "基準情景" : "基准情景"} body={language === "EN" ? "Growth is resilient but yields and oil remain elevated; market and sector dispersion persists." : language === "TW" ? "增長有韌性但收益率和油價仍高；市場與板塊分化持續。" : "增长有韧性但收益率和油价仍高；市场与板块分化持续。"} tone="base"/><Scenario title={language === "EN" ? "Negative" : language === "TW" ? "負面情景" : "负面情景"} body={language === "EN" ? "Inflation/oil shock lifts yields while AI guidance or funding commentary weakens." : language === "TW" ? "通脹／油價衝擊推高收益率，同時AI指引或融資論述轉弱。" : "通胀／油价冲击推高收益率，同时AI指引或融资论述转弱。"} tone="bad"/></div></section>
  </main>;

  const Week = () => <main className="pb-12"><Hero kicker="THIS WEEK / VERIFICATION AGENDA" title={t.weekTitle} body={language === "EN" ? "The calendar matters only where it can change the rates, earnings or valuation thesis. Every row carries a positive and negative confirmation condition." : language === "TW" ? "日曆只在能改變利率、盈利或估值論點時才重要。每一列均有正面與負面確認條件。" : "日历只在能改变利率、盈利或估值论点时才重要。每一列均有正面与负面确认条件。"}/>
    <section className="bg-[#F5F7FA] px-5 py-10 sm:px-10 lg:px-[var(--layout-padding)]"><div className="mx-auto max-w-[1200px] space-y-4">{weeklyRows.map((row: any, index: number) => <article key={row.event} className="grid gap-5 rounded-[12px] border border-[#E4E6EA] bg-white p-6 lg:grid-cols-[.7fr_1.45fr_1fr_1fr]"><div><p className="font-mono text-[10px] font-bold tracking-[.14em] text-[#0040FF]">0{index + 1}</p><p className="mt-4 font-display text-2xl">{row.event}</p><p className="mt-3 flex items-center gap-2 font-mono text-xs text-[#59657A]"><CalendarDays size={14}/>{row.when}</p></div><p className="text-sm leading-7 text-[#59657A]">{row.explanation || (index === 0 ? "Growth and inflation must be read together: the same release changes the policy-rate and valuation frame." : index === 1 ? "This is the direct AI infrastructure fundamental test, not a blanket technology proxy." : index === 2 ? "Separate confirmed policy communication from post-speech market interpretation." : "Treat this as risk-premium monitoring rather than a deterministic market call.")}</p><p className="border-l-2 border-[#10B99A] pl-4 text-sm leading-6 text-[#17733B]"><CheckCircle2 className="mr-2 inline" size={15}/><strong>{t.positive} · </strong>{row.positive}</p><p className="border-l-2 border-[#F9584A] pl-4 text-sm leading-6 text-[#C22F26]"><CircleAlert className="mr-2 inline" size={15}/><strong>{t.negative} · </strong>{row.negative}</p></article>)}</div></section>
    <section className="mx-auto max-w-[1200px] px-5 py-12 sm:px-10 lg:px-[var(--layout-padding)]"><p className="section-kicker">AI / MEMORY INDUSTRY SIGNALS</p><div className="mt-6 grid gap-5 lg:grid-cols-3">{industry.map(([title, fact, status]) => <article key={title} className="rounded-[12px] border border-[#E4E6EA] bg-white p-6"><span className={`rounded-full px-2 py-1 font-mono text-[10px] font-bold ${status.includes("unconfirmed") || status.includes("未确认") || status.includes("未確認") ? "bg-[#F6C82A]/20 text-[#765D00]" : "bg-[#E8F8F2] text-[#17733B]"}`}>{status}</span><p className="mt-5 font-display text-2xl">{title}</p><p className="mt-5 text-sm leading-7 text-[#59657A]">{fact}</p></article>)}</div></section>
    <section className="bg-[#0A0D14] px-5 py-12 text-white sm:px-10 lg:px-[var(--layout-padding)]"><div className="mx-auto max-w-[1200px]"><p className="font-mono text-[10px] tracking-[.16em] text-[#478DFF]">GEOPOLITICS / TRADE RISK</p><p className="mt-5 max-w-4xl text-[16px] leading-8 text-[#EDF1F7]">{language === "EN" ? "Iranian threats around Gulf oil exports and the U.S.–Canada trade escalation are monitored as risk-premium variables. They enter the market thesis only if they create observable oil, freight, inflation or company-level evidence; they are not a reason to pre-state a trade outcome." : language === "TW" ? "伊朗對海灣石油出口的威脅及美加貿易升級被監測為風險溢價變量。只有它們形成可觀察的油價、運費、通脹或公司層面證據時才進入市場論點；不能預先寫成交易結論。" : "伊朗对海湾石油出口的威胁及美加贸易升级被监测为风险溢价变量。只有它们形成可观察的油价、运费、通胀或公司层面证据时才进入市场论点；不能预先写成交易结论。"}</p></div></section>
  </main>;

  const Sources = () => <main className="mx-auto max-w-[1200px] px-5 py-10 sm:px-10 lg:px-[var(--layout-padding)]"><p className="section-kicker">SOURCES / AUDIT TRAIL</p><h1 className="section-title mt-3">{t.sourceTitle}</h1><p className="mt-5 max-w-4xl text-[16px] leading-7 text-[#59657A]">{language === "EN" ? "The report separates completed-session facts, post-weekend developments, official schedules and unconfirmed industry reports. Bloomberg was not used through a verified terminal, BLPAPI or Data License entitlement." : language === "TW" ? "本報告分開完成交易時段事實、週末後發展、官方日程及未確認產業報道。未使用經驗證的Bloomberg Terminal、BLPAPI或Data License權限。" : "本报告分开完成交易时段事实、周末后发展、官方日程及未确认产业报道。未使用经验证的Bloomberg Terminal、BLPAPI或Data License权限。"}</p><div className="mt-8 space-y-3">{sources.map((row: any) => <a key={`${row.id}-${row.label}`} href={row.url} target="_blank" rel="noreferrer" className="group flex items-center justify-between gap-4 rounded-[12px] border border-[#E4E6EA] bg-white p-5 transition hover:border-[#0040FF]"><div><p className="font-mono text-[10px] font-bold tracking-[.14em] text-[#0040FF]">[{row.id}] {row.market.toUpperCase()} · {row.tier}</p><p className="mt-2 text-sm text-[#0A0D14]">{row.label}</p></div><ExternalLink className="shrink-0 text-[#59657A] group-hover:text-[#0040FF]" size={18}/></a>)}</div><p className="mt-10 border-t border-[#E4E6EA] pt-6 text-xs leading-6 text-[#59657A]">{t.disclosure}</p></main>;

  return <div className="bit-v3 bit-page min-h-screen bg-white text-[#0A0D14]"><header className="bit-reference-header sticky top-0 z-30 bg-white"><div className="mx-auto flex max-w-[1400px] items-center justify-between gap-6 px-5 py-4 sm:px-10 lg:px-[var(--layout-padding)]"><div className="flex min-w-0 items-center gap-4 sm:gap-8"><div className="flex shrink-0 items-center gap-2" aria-label="BIT"><img src={`${base}brand/BIT-Logo-blue.svg`} alt="" className="h-8 w-8 rounded-[8px] object-contain"/><img src={`${base}brand/BIT-Logo-black.svg`} alt="BIT" className="bit-wordmark-crop"/></div><div className="hidden h-14 w-px shrink-0 bg-[#DDD5C8] sm:block"/><div className="min-w-0"><p className="font-mono text-[10px] font-medium tracking-[.17em] text-[#5B6473] sm:text-[13px]">{t.edition}</p><p className="mt-2 truncate text-[13px] font-medium text-[#5B6473] sm:text-[17px]">{t.asof}</p></div></div><div className="hidden items-center gap-2 xl:flex"><div className="inline-flex rounded-[8px] border border-[#E4E6EA] bg-white p-1">{(["TW", "CN", "EN"] as Language[]).map((lang) => <button key={lang} onClick={() => navigate(section, lang)} className={`bit-action px-2.5 py-1.5 font-mono text-[10px] font-bold ${language === lang ? "bg-[#0040FF] text-white" : "text-[#59657A]"}`}>{lang}</button>)}</div><button onClick={() => window.print()} className="bit-action hidden items-center gap-2 border border-[#0040FF] px-3 py-2 font-mono text-[10px] font-bold text-[#0040FF] 2xl:inline-flex"><Printer size={13}/>{t.print}</button></div></div><div className="mx-auto flex max-w-[1400px] gap-7 overflow-x-auto px-5 sm:gap-10 sm:px-10 lg:px-[var(--layout-padding)]">{(Object.keys(t.nav) as Section[]).map((key) => <button key={key} onClick={() => navigate(key)} className={`bit-action whitespace-nowrap border-b-[3px] px-0 pb-5 pt-4 text-[18px] font-semibold sm:text-[26px] ${section === key ? "border-[#E4DCCF] text-[#0040FF]" : "border-transparent text-[#5B6473] hover:text-[#0040FF]"}`}>{t.nav[key]}</button>)}<a href={`${base}?date=2026-08-21&lang=${language}`} className="ml-auto hidden whitespace-nowrap border-b-[3px] border-transparent pb-5 pt-4 font-mono text-[10px] text-[#59657A] hover:text-[#0040FF] 2xl:block">{t.history}<TrendingUp className="ml-1 inline" size={12}/></a></div></header>{section === "overview" ? <Overview/> : section === "us" ? <US/> : section === "hk" ? <HK/> : section === "cross" ? <Cross/> : section === "week" ? <Week/> : <Sources/>}</div>;
}

function Hero({ kicker, title, body }: { kicker: string; title: string; body: string }) { return <section className="mx-auto max-w-[1200px] px-5 py-10 sm:px-10 lg:px-[var(--layout-padding)]"><p className="section-kicker">{kicker}</p><h1 className="section-title mt-3">{title}</h1><p className="mt-5 max-w-4xl text-[17px] leading-8 text-[#59657A]">{body}</p></section>; }
function Card({ label, value, body, action, onClick, secondary }: { label: string; value: string; body: string; action: string; onClick: () => void; secondary?: boolean }) { return <article className="rounded-[12px] border border-[#E4E6EA] bg-white p-6"><p className="section-kicker">{label}</p><p className="mt-4 font-mono text-2xl font-semibold text-[#0A0D14]">{value}</p><p className="mt-4 text-sm leading-6 text-[#59657A]">{body}</p><button onClick={onClick} className={`bit-action mt-7 inline-flex items-center gap-2 px-4 py-2 text-xs font-bold ${secondary ? "border border-[#0040FF] text-[#0040FF]" : "bg-[#0040FF] text-white"}`}>{action}<ArrowRight size={14}/></button></article>; }
function ReadingLayer({ title, body, prompts, mode, setMode, labels }: { title: string; body: string; prompts: string[]; mode: Mode; setMode: (mode: Mode) => void; labels: any }) { return <section className="mt-12 border-t border-[#E4E6EA] pt-10"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="section-kicker">READING MODE / CONSISTENCY LAYER</p><h2 className="mt-3 font-display text-3xl">{title}</h2></div><div className="inline-flex rounded-[8px] border border-[#E4E6EA] bg-[#F5F7FA] p-1">{(["education", "analysis"] as Mode[]).map((item) => <button key={item} onClick={() => setMode(item)} className={`bit-action px-3 py-2 text-xs font-bold ${mode === item ? "bg-[#0040FF] text-white" : "text-[#59657A]"}`}>{labels[item]}</button>)}</div></div><p className="mt-5 max-w-4xl text-[16px] leading-8 text-[#59657A]">{body}</p><div className="mt-6 grid gap-4 lg:grid-cols-3">{prompts.map((prompt) => <article key={prompt} className="rounded-[12px] border border-[#E4E6EA] bg-white p-5 text-sm leading-7 text-[#0A0D14]"><Info className="mb-4 text-[#0040FF]" size={17}/>{prompt}</article>)}</div></section>; }
function EvidenceCard({ title, fact, implication, watch, t, badge }: { title: string; fact: string; implication: string; watch: string; t: any; badge?: string }) { return <article className="rounded-[12px] border border-[#E4E6EA] bg-white p-6">{badge && <span className="rounded-full bg-[#F6C82A]/20 px-2 py-1 font-mono text-[10px] font-bold text-[#765D00]">{badge}</span>}<p className="mt-4 font-display text-2xl">{title}</p><p className="mt-5 text-sm leading-7 text-[#59657A]"><strong className="text-[#0A0D14]">{t.fact} · </strong>{fact}</p><p className="mt-5 border-l-2 border-[#0040FF] pl-4 text-sm leading-7 text-[#0A0D14]"><strong>{t.meaning} · </strong>{implication}</p><p className="mt-5 text-sm leading-7 text-[#59657A]"><strong className="text-[#0A0D14]">{t.next} · </strong>{watch}</p></article>; }
function SimpleCard({ title, body }: { title: string; body: string }) { return <article className="rounded-[12px] border border-[#E4E6EA] bg-white p-6"><p className="font-display text-2xl">{title}</p><p className="mt-5 text-sm leading-7 text-[#59657A]">{body}</p></article>; }
function Scenario({ title, body, tone }: { title: string; body: string; tone: "good" | "base" | "bad" }) { const cls = tone === "good" ? "border-[#10B99A] text-[#17733B]" : tone === "bad" ? "border-[#F9584A] text-[#C22F26]" : "border-[#E4E6EA] text-[#59657A]"; return <article className={`border-l-2 bg-white p-6 ${cls}`}><p className="font-mono text-[10px] font-bold tracking-[.14em]">{title.toUpperCase()}</p><p className="mt-5 text-sm leading-7 text-[#0A0D14]">{body}</p></article>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="border-l-2 border-[#0040FF] pl-3"><p className="font-mono text-[10px] tracking-[.12em] text-[#59657A]">{label}</p><p className="mt-2 font-mono text-2xl font-semibold">{value}</p></div>; }
